//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/MultiFPS/Scripts/Inputs/MultiFPSInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MultiFPSInputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MultiFPSInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MultiFPSInputs"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""f8191ba9-a8ac-449c-a647-98b626e0b8af"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""b383bbe8-93fb-40df-a822-c008244df50f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TakeItem1"",
                    ""type"": ""Button"",
                    ""id"": ""0d63f3e5-5303-42e5-a180-c700b0f31889"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TakeItem2"",
                    ""type"": ""Button"",
                    ""id"": ""2dffc380-b350-4a70-8d33-f70c115c0531"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TakeItem3"",
                    ""type"": ""Button"",
                    ""id"": ""f4bc4f5f-1ac3-45df-96b5-22dfd013ce41"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TakeItem4"",
                    ""type"": ""Button"",
                    ""id"": ""32714336-ebfc-4964-964e-b46b1bec03c4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TakeItem_Bomb"",
                    ""type"": ""Button"",
                    ""id"": ""a628a2ef-8bba-411b-98a9-85147fd7583a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TakePreviousItem"",
                    ""type"": ""Button"",
                    ""id"": ""1238d51a-f219-443b-9dce-4d8a352405d5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interaction"",
                    ""type"": ""Button"",
                    ""id"": ""a7753a4a-34f3-449c-b43b-deeb81d56819"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DropItem"",
                    ""type"": ""Button"",
                    ""id"": ""199e0937-d0d5-45d4-9572-494aa93c0222"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reload"",
                    ""type"": ""Button"",
                    ""id"": ""5da9d1d1-63ff-48da-85e5-1a3b7eedc678"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""54c3cbf2-0fbe-4fb6-8ac9-0e0ea9d0c5a8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MeleeAttack"",
                    ""type"": ""Button"",
                    ""id"": ""4151b6e7-d0b7-49a1-9ced-36a6540edd29"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Fire1Hold"",
                    ""type"": ""Value"",
                    ""id"": ""7e6ca49a-1f13-48b3-b0af-a50f21b886f6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Fire2Hold"",
                    ""type"": ""Value"",
                    ""id"": ""7639cf51-6945-4781-9c8f-d4c2d513b628"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Value"",
                    ""id"": ""1d9db3cd-5aa6-49b2-8b74-e271d95ae00d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Value"",
                    ""id"": ""7981370e-a649-4d14-8f99-b420460eea57"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""bfa06df5-44a9-4ad4-9114-fc45a25cbebf"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WSAD"",
                    ""id"": ""23a12387-9827-428a-831d-5821176b1418"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9f37d884-331f-4250-8bdc-4c418dcf40a4"",
                    ""path"": ""<Keyboard>/#(W)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""645c4e8a-57ca-4da7-9560-2713ce4d8f14"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""89bcc251-db39-4c3a-b631-8a49283ffe92"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""057cf1bf-f501-4f93-878e-8b1c42e5dbb3"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""55125485-3975-48ca-81f5-398d5368e79e"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TakeItem1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b9f3a107-a855-4486-a0ff-dd8f79e869af"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TakeItem2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cf4d9af7-e865-4db4-b643-46c61e5fdac6"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TakeItem3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fe2e48df-d3a0-415a-8ed5-5aafdb1102ab"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TakeItem4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2080687d-0b8e-4474-8729-320e5765ca97"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fire1Hold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""21df1f0f-4666-4254-a955-69056bfd3351"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fire2Hold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ddc69f71-85b7-4c38-8071-bf0fff539bac"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TakeItem_Bomb"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""16aa5661-af1b-4ddc-9306-028957a184df"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86c837db-2c76-4f1f-927f-2886586ac12b"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MeleeAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4ed2e245-6ace-454e-911e-912194ca2886"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""254d457c-eb17-4aa3-a800-d89c05b513d1"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b5b576c0-6e09-492c-808e-0fa47102a119"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0701390a-1e1f-42bd-a35a-b2b1bb9a8ef8"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00295ea0-5f05-4163-820b-d0029c49f79b"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TakePreviousItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""29c712dc-182b-4b34-a542-41375ee347b1"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""024cff43-5383-40bd-8f1e-4c4e657cb86f"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DropItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Movement = m_Player.FindAction("Movement", throwIfNotFound: true);
        m_Player_TakeItem1 = m_Player.FindAction("TakeItem1", throwIfNotFound: true);
        m_Player_TakeItem2 = m_Player.FindAction("TakeItem2", throwIfNotFound: true);
        m_Player_TakeItem3 = m_Player.FindAction("TakeItem3", throwIfNotFound: true);
        m_Player_TakeItem4 = m_Player.FindAction("TakeItem4", throwIfNotFound: true);
        m_Player_TakeItem_Bomb = m_Player.FindAction("TakeItem_Bomb", throwIfNotFound: true);
        m_Player_TakePreviousItem = m_Player.FindAction("TakePreviousItem", throwIfNotFound: true);
        m_Player_Interaction = m_Player.FindAction("Interaction", throwIfNotFound: true);
        m_Player_DropItem = m_Player.FindAction("DropItem", throwIfNotFound: true);
        m_Player_Reload = m_Player.FindAction("Reload", throwIfNotFound: true);
        m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
        m_Player_MeleeAttack = m_Player.FindAction("MeleeAttack", throwIfNotFound: true);
        m_Player_Fire1Hold = m_Player.FindAction("Fire1Hold", throwIfNotFound: true);
        m_Player_Fire2Hold = m_Player.FindAction("Fire2Hold", throwIfNotFound: true);
        m_Player_Sprint = m_Player.FindAction("Sprint", throwIfNotFound: true);
        m_Player_Crouch = m_Player.FindAction("Crouch", throwIfNotFound: true);
        m_Player_Look = m_Player.FindAction("Look", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Movement;
    private readonly InputAction m_Player_TakeItem1;
    private readonly InputAction m_Player_TakeItem2;
    private readonly InputAction m_Player_TakeItem3;
    private readonly InputAction m_Player_TakeItem4;
    private readonly InputAction m_Player_TakeItem_Bomb;
    private readonly InputAction m_Player_TakePreviousItem;
    private readonly InputAction m_Player_Interaction;
    private readonly InputAction m_Player_DropItem;
    private readonly InputAction m_Player_Reload;
    private readonly InputAction m_Player_Jump;
    private readonly InputAction m_Player_MeleeAttack;
    private readonly InputAction m_Player_Fire1Hold;
    private readonly InputAction m_Player_Fire2Hold;
    private readonly InputAction m_Player_Sprint;
    private readonly InputAction m_Player_Crouch;
    private readonly InputAction m_Player_Look;
    public struct PlayerActions
    {
        private @MultiFPSInputs m_Wrapper;
        public PlayerActions(@MultiFPSInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Player_Movement;
        public InputAction @TakeItem1 => m_Wrapper.m_Player_TakeItem1;
        public InputAction @TakeItem2 => m_Wrapper.m_Player_TakeItem2;
        public InputAction @TakeItem3 => m_Wrapper.m_Player_TakeItem3;
        public InputAction @TakeItem4 => m_Wrapper.m_Player_TakeItem4;
        public InputAction @TakeItem_Bomb => m_Wrapper.m_Player_TakeItem_Bomb;
        public InputAction @TakePreviousItem => m_Wrapper.m_Player_TakePreviousItem;
        public InputAction @Interaction => m_Wrapper.m_Player_Interaction;
        public InputAction @DropItem => m_Wrapper.m_Player_DropItem;
        public InputAction @Reload => m_Wrapper.m_Player_Reload;
        public InputAction @Jump => m_Wrapper.m_Player_Jump;
        public InputAction @MeleeAttack => m_Wrapper.m_Player_MeleeAttack;
        public InputAction @Fire1Hold => m_Wrapper.m_Player_Fire1Hold;
        public InputAction @Fire2Hold => m_Wrapper.m_Player_Fire2Hold;
        public InputAction @Sprint => m_Wrapper.m_Player_Sprint;
        public InputAction @Crouch => m_Wrapper.m_Player_Crouch;
        public InputAction @Look => m_Wrapper.m_Player_Look;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @TakeItem1.started += instance.OnTakeItem1;
            @TakeItem1.performed += instance.OnTakeItem1;
            @TakeItem1.canceled += instance.OnTakeItem1;
            @TakeItem2.started += instance.OnTakeItem2;
            @TakeItem2.performed += instance.OnTakeItem2;
            @TakeItem2.canceled += instance.OnTakeItem2;
            @TakeItem3.started += instance.OnTakeItem3;
            @TakeItem3.performed += instance.OnTakeItem3;
            @TakeItem3.canceled += instance.OnTakeItem3;
            @TakeItem4.started += instance.OnTakeItem4;
            @TakeItem4.performed += instance.OnTakeItem4;
            @TakeItem4.canceled += instance.OnTakeItem4;
            @TakeItem_Bomb.started += instance.OnTakeItem_Bomb;
            @TakeItem_Bomb.performed += instance.OnTakeItem_Bomb;
            @TakeItem_Bomb.canceled += instance.OnTakeItem_Bomb;
            @TakePreviousItem.started += instance.OnTakePreviousItem;
            @TakePreviousItem.performed += instance.OnTakePreviousItem;
            @TakePreviousItem.canceled += instance.OnTakePreviousItem;
            @Interaction.started += instance.OnInteraction;
            @Interaction.performed += instance.OnInteraction;
            @Interaction.canceled += instance.OnInteraction;
            @DropItem.started += instance.OnDropItem;
            @DropItem.performed += instance.OnDropItem;
            @DropItem.canceled += instance.OnDropItem;
            @Reload.started += instance.OnReload;
            @Reload.performed += instance.OnReload;
            @Reload.canceled += instance.OnReload;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @MeleeAttack.started += instance.OnMeleeAttack;
            @MeleeAttack.performed += instance.OnMeleeAttack;
            @MeleeAttack.canceled += instance.OnMeleeAttack;
            @Fire1Hold.started += instance.OnFire1Hold;
            @Fire1Hold.performed += instance.OnFire1Hold;
            @Fire1Hold.canceled += instance.OnFire1Hold;
            @Fire2Hold.started += instance.OnFire2Hold;
            @Fire2Hold.performed += instance.OnFire2Hold;
            @Fire2Hold.canceled += instance.OnFire2Hold;
            @Sprint.started += instance.OnSprint;
            @Sprint.performed += instance.OnSprint;
            @Sprint.canceled += instance.OnSprint;
            @Crouch.started += instance.OnCrouch;
            @Crouch.performed += instance.OnCrouch;
            @Crouch.canceled += instance.OnCrouch;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @TakeItem1.started -= instance.OnTakeItem1;
            @TakeItem1.performed -= instance.OnTakeItem1;
            @TakeItem1.canceled -= instance.OnTakeItem1;
            @TakeItem2.started -= instance.OnTakeItem2;
            @TakeItem2.performed -= instance.OnTakeItem2;
            @TakeItem2.canceled -= instance.OnTakeItem2;
            @TakeItem3.started -= instance.OnTakeItem3;
            @TakeItem3.performed -= instance.OnTakeItem3;
            @TakeItem3.canceled -= instance.OnTakeItem3;
            @TakeItem4.started -= instance.OnTakeItem4;
            @TakeItem4.performed -= instance.OnTakeItem4;
            @TakeItem4.canceled -= instance.OnTakeItem4;
            @TakeItem_Bomb.started -= instance.OnTakeItem_Bomb;
            @TakeItem_Bomb.performed -= instance.OnTakeItem_Bomb;
            @TakeItem_Bomb.canceled -= instance.OnTakeItem_Bomb;
            @TakePreviousItem.started -= instance.OnTakePreviousItem;
            @TakePreviousItem.performed -= instance.OnTakePreviousItem;
            @TakePreviousItem.canceled -= instance.OnTakePreviousItem;
            @Interaction.started -= instance.OnInteraction;
            @Interaction.performed -= instance.OnInteraction;
            @Interaction.canceled -= instance.OnInteraction;
            @DropItem.started -= instance.OnDropItem;
            @DropItem.performed -= instance.OnDropItem;
            @DropItem.canceled -= instance.OnDropItem;
            @Reload.started -= instance.OnReload;
            @Reload.performed -= instance.OnReload;
            @Reload.canceled -= instance.OnReload;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @MeleeAttack.started -= instance.OnMeleeAttack;
            @MeleeAttack.performed -= instance.OnMeleeAttack;
            @MeleeAttack.canceled -= instance.OnMeleeAttack;
            @Fire1Hold.started -= instance.OnFire1Hold;
            @Fire1Hold.performed -= instance.OnFire1Hold;
            @Fire1Hold.canceled -= instance.OnFire1Hold;
            @Fire2Hold.started -= instance.OnFire2Hold;
            @Fire2Hold.performed -= instance.OnFire2Hold;
            @Fire2Hold.canceled -= instance.OnFire2Hold;
            @Sprint.started -= instance.OnSprint;
            @Sprint.performed -= instance.OnSprint;
            @Sprint.canceled -= instance.OnSprint;
            @Crouch.started -= instance.OnCrouch;
            @Crouch.performed -= instance.OnCrouch;
            @Crouch.canceled -= instance.OnCrouch;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnTakeItem1(InputAction.CallbackContext context);
        void OnTakeItem2(InputAction.CallbackContext context);
        void OnTakeItem3(InputAction.CallbackContext context);
        void OnTakeItem4(InputAction.CallbackContext context);
        void OnTakeItem_Bomb(InputAction.CallbackContext context);
        void OnTakePreviousItem(InputAction.CallbackContext context);
        void OnInteraction(InputAction.CallbackContext context);
        void OnDropItem(InputAction.CallbackContext context);
        void OnReload(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnMeleeAttack(InputAction.CallbackContext context);
        void OnFire1Hold(InputAction.CallbackContext context);
        void OnFire2Hold(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
        void OnCrouch(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
    }
}
